language: python
python:
  - "2.7"
notifications:
    email:
        admin@unary.ca
env:
    - PYTHONPATH=./
install: pip install coveralls
script:
    - py.test test/test_distance.py
    - coverage run --source=pyjarowinkler test/test_distance.py
after_success:
    coveralls